---
title: "group_41_ca_ej"
author: "Mukta Kelkar & Nikole Vannest"
date: "11/24/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(here)
```

# Read in data

```{r}
ces <- read.csv(here("data", "ces3demographics.csv")) %>% 
  clean_names()
```

# Visualize data

```{r}
ces %>% 
  ggplot(aes(x = white, y = ces_3_0_score)) + 
  geom_hex() +
  labs(x = "Percentage of Population that is White",
      y = "CES 3.0 Score",
      title = "Relationship between demographics and CES Score in CA census tracts") +
  scale_fill_gradient(low = "navy", high = "orange") +
  theme_minimal()
```

**Overall Takeaways** In general, it looks like there is a negative relationship between CES 3.0 score and the percent of population that identifies as white. There are a larger number of census tracts taken when the percent of population that is white equals or is close to 0, as well as when it is greater than or equal to 75. 